/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define GPIOAEN		(1U << 0)
#define GPIOBEN		(1U << 1)
#define GPIOCEN		(1U << 2)
#define GPIODEN		(1U << 3)
#define GPIOEEN		(1U << 4)
#define GPIOFEN		(1U << 5)
#define GPIOGEN		(1U << 6)
#define GPIOHEN		(1U << 7)
#define GPIOIEN		(1U << 8)

#define TIM1EN		(1U << 0)
#define ADC1EN		(1U << 8)

int main(void)
{
	// Enable FPU
#if defined (__FPU_PRESENT) && (__FPU_PRESENT == 1U)
	SCB->CPACR |= ((3UL << 10*2)|(3UL << 11*2));  // set CP10 and CP11 Full Access
	__DSB();                                      // Ensures completion of memory access
	__ISB();                                      // Ensures instruction synchronization
#endif

	// Enable HSE
	RCC->CR |= RCC_CR_HSEON;
	while (!(RCC->CR & RCC_CR_HSERDY));

	// Set system clock to 60MHz - HSE is 8MHz
	RCC->PLLCFGR =
			(8U << RCC_PLLCFGR_PLLM_Pos) |   // M
			(120U << RCC_PLLCFGR_PLLN_Pos) | // N
			(0U << RCC_PLLCFGR_PLLP_Pos) |   // P = 2 (encoded as 0)
			RCC_PLLCFGR_PLLSRC_HSE;

	// Enable PLL
	RCC->CR |= RCC_CR_PLLON;
	while (!(RCC->CR & RCC_CR_PLLRDY));
	FLASH->ACR = FLASH_ACR_LATENCY_2WS; // Flash latency for high speed reading

	// Switch to PLL
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL);

	// Switch to HSE - NOT REQUIRED HERE
	//RCC->CFGR |= RCC_CFGR_SW_HSE;
	//while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_HSE);

	// Turn off HSI
	RCC->CR &= ~RCC_CR_HSION;


	//ENABLE ADC1 GPIO CLOCK
	RCC->AHB1ENR |= GPIOBEN;
	//SET ANALOG MODE FOR PINS 8/9 IN PORT B
	GPIOB->MODER &= ~((GPIO_MODER_MODER8) | (GPIO_MODER_MODER9));
	GPIOB->MODER |= (GPIO_MODER_MODER8) | (GPIO_MODER_MODER9);
	//ENABLE ADC1 PERIPHERAL CLOCK
	RCC->APB2ENR |= ADC1EN;
	/*
	 * B0 ADC1 IN8
	 * B1 ADC2 IN9
	 */

	//ENABLE TIM1 GPIO CLOCK
	RCC->AHB1ENR |= GPIOEEN;
	//SET ALTERNATE FUNCTION 1 MODE FOR PINS 9/11/13/14 IN PORT E
	GPIOE->MODER &= ~((GPIO_MODER_MODER9) | (GPIO_MODER_MODER11) | (GPIO_MODER_MODER13) | (GPIO_MODER_MODER14));
	GPIOE->MODER |= (GPIO_MODER_MODER9_1) | (GPIO_MODER_MODER11_1) | (GPIO_MODER_MODER13_1) | (GPIO_MODER_MODER14_1);

	GPIOE->AFR[1] &= ~((GPIO_AFRH_AFSEL9) | (GPIO_AFRH_AFSEL11) | (GPIO_AFRH_AFSEL13) | (GPIO_AFRH_AFSEL14));
	GPIOE->AFR[1] |= (GPIO_AFRH_AFSEL9_0) | (GPIO_AFRH_AFSEL11_0) | (GPIO_AFRH_AFSEL13_0) | (GPIO_AFRH_AFSEL14_0);
	//ENABLE TIM1 PERIPHERAL CLOCK
	RCC->APB2ENR |= TIM1EN;
	/*
	 *  E9 ch1
	 *  E11 ch2
	 *  E13 ch3
	 *  E14 ch4
	 */

	while(1){

	}
}
